export const manifest = {
  workflow_id: "ftg_revamped_flow_v1",
  workflow_name: "FTG - Dimension & Weight Capture",
  steps: [
    {
      step_id: 1,
      screen: "packaging_options",
      screenshot: "/screens/ftg_11.png",
      title: "Choose Packaging Type",
      instruction: "Tap 'Ships In Own Box' to select the packaging type for this product.",
      tip: "SIOB means the product ships in its original box — no repackaging needed.",
      expected_action: "TAP",
      on_wrong_action: "That's not right. Please tap 'Ships In Own Box'.",
      tap_target: { x: 3, y: 35, width: 94, height: 12 },
    },
    {
      step_id: 2,
      screen: "packaging_options",
      screenshot: "/screens/ftg_11.png",
      title: "Proceed to Next Step",
      instruction: "Now tap the 'Next' button at the bottom to continue.",
      tip: null,
      expected_action: "TAP",
      on_wrong_action: "Tap the Next button at the bottom of the screen.",
      tap_target: { x: 4, y: 89, width: 92, height: 7 },
    },
    {
      step_id: 3,
      screen: "product_identifiers",
      screenshot: "/screens/ftg_06.png",
      title: "Select Product Category",
      instruction: "Tap the 'Product Category' dropdown and select the correct category.",
      tip: "Product category is mandatory when SDP config is enabled for your FC.",
      expected_action: "TAP",
      on_wrong_action: "Please tap the Product Category dropdown.",
      tap_target: { x: 4, y: 33, width: 92, height: 7 },
    },
    {
      step_id: 4,
      screen: "product_identifiers",
      screenshot: "/screens/ftg_06.png",
      title: "Enter Scannable ID",
      instruction: "Type the Scannable ID if available. This field is optional — skip if not needed.",
      tip: "Scannable ID helps identify the product during receiving.",
      expected_action: "TYPE",
      on_wrong_action: "Type the Scannable ID or tap Next to skip.",
      tap_target: { x: 4, y: 43, width: 92, height: 7 },
    },
    {
      step_id: 5,
      screen: "product_identifiers",
      screenshot: "/screens/ftg_06.png",
      title: "Continue to Dimensions",
      instruction: "Tap 'Next' to proceed to the Dimension & Weight capture screen.",
      tip: "Product Image URL is optional — you can leave it blank.",
      expected_action: "TAP",
      on_wrong_action: "Tap the Next button at the bottom.",
      tap_target: { x: 4, y: 89, width: 92, height: 7 },
    },
    {
      step_id: 6,
      screen: "dimension_vmeasure",
      screenshot: "/screens/ftg_08.png",
      title: "V-Measure Mode",
      instruction: "V-Measure is selected by default. Place the product on the machine.",
      tip: "The barcode format is DLVSKU followed by the SKU number.",
      expected_action: "VERIFY",
      on_wrong_action: "Check that V-Measure tab is selected.",
      tap_target: { x: 8, y: 30, width: 45, height: 5 },
    },
    {
      step_id: 7,
      screen: "dimension_vmeasure",
      screenshot: "/screens/ftg_08.png",
      title: "Scan Barcode",
      instruction: "Scan the barcode shown on screen using the V-Measure machine.",
      tip: "The machine auto-polls every 2 seconds after scanning.",
      expected_action: "SCAN",
      on_wrong_action: "Scan the barcode displayed on the screen.",
      tap_target: { x: 10, y: 42, width: 80, height: 20 },
    },
    {
      step_id: 8,
      screen: "dimension_results",
      screenshot: "/screens/ftg_10.png",
      title: "Verify Dimensions",
      instruction: "Check the captured L × W × H and Weight values. Tap Recapture if incorrect.",
      tip: "If dimensions exceed machine limits, you'll need to use Manual mode or a different machine.",
      expected_action: "VERIFY",
      on_wrong_action: "Review the dimension values shown on screen.",
      tap_target: { x: 8, y: 45, width: 84, height: 15 },
    },
    {
      step_id: 9,
      screen: "dimension_results",
      screenshot: "/screens/ftg_10.png",
      title: "Save Dimensions",
      instruction: "Everything looks good! Tap 'Save' to complete the FTG process.",
      tip: "After saving, you'll be taken back to the SKU search screen.",
      expected_action: "TAP",
      on_wrong_action: "Tap the Save button to finalize.",
      tap_target: { x: 50, y: 89, width: 45, height: 7 },
    },
  ],
  quiz_breaks: [
    {
      after_step: 2,
      questions: [
        {
          question: "What does SIOCB stand for?",
          options: ["Ships In Own Box", "Ships In Own Case Box", "Standard Item Own Container", "Ships In Original Case Box"],
          correct: 1,
        },
        {
          question: "When you select SIOCB, what extra field appears?",
          options: ["Weight", "Items Per Box", "Barcode", "Product Image"],
          correct: 1,
        },
      ],
    },
    {
      after_step: 5,
      questions: [
        {
          question: "Is Product Category mandatory on the Product Identifiers screen?",
          options: ["Always mandatory", "Only when SDP config is enabled", "Never mandatory", "Only for SIOCB"],
          correct: 1,
        },
      ],
    },
    {
      after_step: 9,
      questions: [
        {
          question: "Who can use Manual mode for dimension entry?",
          options: ["Anyone", "Only users with UMS permission", "Only managers", "Only IT team"],
          correct: 1,
        },
        {
          question: "What happens if V-Measure dimensions exceed machine limits?",
          options: ["Data saves anyway", "Error shown — use manual or different machine", "App crashes", "Dimensions are auto-corrected"],
          correct: 1,
        },
      ],
    },
  ],
};
